# Generated by Django 6.0.2 on 2026-02-22 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='idcategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=30)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=100, null=True)),
                ('icono', models.TextField(blank=True, db_column='icono', null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idusuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='nombres', max_length=40)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=40)),
                ('correo', models.CharField(db_column='correo', max_length=255, unique=True)),
                ('contrasena', models.CharField(db_column='contrasena', max_length=255)),
                ('fechanac', models.DateTimeField(blank=True, db_column='fechanac', null=True)),
                ('suscrito', models.BooleanField(db_column='suscrito', default=False)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True, db_column='fecharegistro')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Navicito',
            fields=[
                ('idnavicito', models.AutoField(db_column='idnavicito', primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='nombres', max_length=40)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=40)),
                ('fechanac', models.DateField(blank=True, db_column='fechanac', null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], db_column='genero', max_length=10, null=True)),
                ('avatar', models.TextField(blank=True, db_column='avatar', null=True)),
                ('tutor', models.ForeignKey(db_column='tutorid', on_delete=django.db.models.deletion.CASCADE, to='landing.usuario')),
            ],
            options={
                'db_table': 'navicitos',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idactividad', models.AutoField(db_column='idactividad', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=40)),
                ('tipo', models.CharField(blank=True, choices=[('Juego', 'Juego'), ('Lectura', 'Lectura'), ('Video', 'Video'), ('Ejercicio', 'Ejercicio')], db_column='tipo', max_length=10, null=True)),
                ('recursourl', models.CharField(blank=True, db_column='recursourl', max_length=100, null=True)),
                ('puntuacion', models.IntegerField(blank=True, db_column='puntuacion', null=True)),
                ('dificultad', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], db_column='dificultad', max_length=10, null=True)),
                ('categoria', models.ForeignKey(db_column='idcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.categoria')),
            ],
            options={
                'db_table': 'actividades',
            },
        ),
        migrations.CreateModel(
            name='Metricas',
            fields=[
                ('idmetrica', models.AutoField(db_column='idmetrica', primary_key=True, serialize=False)),
                ('pensamientologico', models.IntegerField(db_column='pensamientologico', default=0)),
                ('lenguajecomunicacion', models.IntegerField(db_column='lenguajecomunicacion', default=0)),
                ('atencion', models.IntegerField(db_column='atencion', default=0)),
                ('ultimaactualizacion', models.DateTimeField(auto_now=True, db_column='ultimaactualizacion')),
                ('navicito', models.OneToOneField(db_column='idnavicito', on_delete=django.db.models.deletion.CASCADE, to='landing.navicito')),
            ],
            options={
                'db_table': 'metricas',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.AutoField(db_column='idhistorial', primary_key=True, serialize=False)),
                ('puntuacionobtenida', models.IntegerField(blank=True, db_column='puntuacionobtenida', null=True)),
                ('duracionsegundos', models.IntegerField(blank=True, db_column='duracionsegundos', null=True)),
                ('completado', models.BooleanField(db_column='completado', default=False)),
                ('fecharealizacion', models.DateTimeField(auto_now_add=True, db_column='fecharealizacion')),
                ('actividad', models.ForeignKey(db_column='idactividad', on_delete=django.db.models.deletion.CASCADE, to='landing.actividad')),
                ('navicito', models.ForeignKey(db_column='idnavicito', on_delete=django.db.models.deletion.CASCADE, to='landing.navicito')),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('idfavoritos', models.AutoField(db_column='idfavoritos', primary_key=True, serialize=False)),
                ('fechaagregado', models.DateTimeField(auto_now_add=True, db_column='fechaagregado')),
                ('actividad', models.ForeignKey(db_column='idactividad', on_delete=django.db.models.deletion.CASCADE, to='landing.actividad')),
                ('navicito', models.ForeignKey(db_column='idnavicito', on_delete=django.db.models.deletion.CASCADE, to='landing.navicito')),
            ],
            options={
                'db_table': 'favoritos',
                'unique_together': {('navicito', 'actividad')},
            },
        ),
    ]
