# Generated by Django 6.0.2 on 2026-03-05 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_conversation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NaviVoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_output_enabled', models.BooleanField(default=True)),
                ('audio_only_mode', models.BooleanField(default=False)),
                ('speech_rate', models.FloatField(default=0.95)),
                ('speech_pitch', models.FloatField(default=1.0)),
                ('speech_lang', models.CharField(default='es-MX', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navi_voice_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'navi_voice_preferences',
            },
        ),
    ]
