# Generated by Django 6.0.2 on 2026-03-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_navivoicepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='navivoicepreference',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
