# Generated by Django 6.0.2 on 2026-03-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_navivoicepreference_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='navivoicepreference',
            name='voice_profile',
            field=models.CharField(default='suave', max_length=20),
        ),
    ]
